# Generated by Django 5.1.8 on 2025-08-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Habit Name")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Habit Description (Optional)",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("dodgerblue", "Bright Blue"),
                            ("crimson", "Tomato"),
                            ("gold", "Gold"),
                            ("lightpink", "Light Pink"),
                            ("olive", "Olive"),
                            ("peru", "Indian Red "),
                            ("slateblue", "Indigo"),
                            ("thistle", "Thistle"),
                        ],
                        default="blue",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="HabitStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("done", models.BooleanField(default=None, null=True)),
            ],
        ),
    ]
