# Generated by Django 5.1.8 on 2025-04-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="end_date",
        ),
        migrations.AddField(
            model_name="habit",
            name="is_unlimited",
            field=models.BooleanField(default=False),
        ),
    ]
