# Generated by Django 5.1.8 on 2025-04-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0002_remove_habit_end_date_habit_is_unlimited"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="author",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.IntegerField(
                choices=[(1, "Daily"), (7, "Weekly"), (30, "Monthly")], default=1
            ),
        ),
    ]
