# Generated by Django 5.1.8 on 2025-09-01 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="habit",
            name="color",
            field=models.CharField(
                choices=[
                    ("#0d6efd", "Blue"),
                    ("#6f42c1", "Indigo"),
                    ("#d63384", "Pink"),
                    ("#dc3545", "Red"),
                    ("#fd7e14", "Orange"),
                    ("#ffc107", "Yellow"),
                    ("#198754", "Green"),
                    ("#0dcaf0", "Teal"),
                    ("#6c757d", "Gray"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="habitstatus",
            name="done",
            field=models.BooleanField(
                default=None,
                help_text="Tracks the completion status: True for done, False for not done, and Null if not yet marked by the user.",
                null=True,
            ),
        ),
    ]
