# Generated by Django 5.1.8 on 2025-04-03 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0003_rename_author_habit_user_alter_habit_frequency"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="name",
            new_name="title",
        ),
    ]
