# Generated by Django 5.1.8 on 2025-04-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0004_rename_name_habit_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="title",
            new_name="name",
        ),
    ]
