# Generated by Django 5.1.8 on 2025-04-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0005_rename_title_habit_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Habit Description (Optional)"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Habit Name"),
        ),
    ]
