# Generated by Django 5.1.8 on 2025-04-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0006_alter_habit_description_alter_habit_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.IntegerField(
                choices=[(1, "Every Day"), (7, "Weekly"), (30, "Monthly")], default=1
            ),
        ),
    ]
