# Generated by Django 5.1.8 on 2025-04-07 11:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0008_habitlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HabitLog",
            new_name="HabitStatus",
        ),
    ]
