# Generated by Django 5.1.8 on 2025-04-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0009_rename_habitlog_habitstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habitstatus",
            name="done",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
