# Generated by Django 5.1.8 on 2025-04-09 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0010_alter_habitstatus_done"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="frequency",
        ),
    ]
