# Generated by Django 5.1.8 on 2025-04-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0011_remove_habit_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="color",
            field=models.CharField(
                choices=[
                    ("lightcoral", "Light Coral"),
                    ("lightblue", "Light Blue"),
                    ("lightgreen", "Light Green"),
                    ("khaki", "Khaki"),
                    ("lightsalmon", "Light Salmon"),
                    ("plum", "Plum"),
                    ("lightpink", "Light Pink"),
                    ("burlywood", "Burly Wood"),
                    ("lightgray", "Light Gray"),
                    ("darkslategray", "Dark Slate Gray"),
                ],
                default="blue",
                max_length=20,
            ),
        ),
    ]
