# Generated by Django 5.1.8 on 2025-04-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0012_alter_habit_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="color",
            field=models.CharField(
                choices=[
                    ("dodgerblue", "Bright Blue"),
                    ("crimson", "Crimson"),
                    ("gold", "Gold"),
                    ("lightpink", "Light Pink"),
                    ("olive", "Olive"),
                    ("peru", "Peru"),
                    ("slateblue", "Slate Blue"),
                    ("thistle", "Thistle"),
                ],
                default="blue",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Habit Description (Optional)",
            ),
        ),
    ]
