# Generated by Django 5.1.8 on 2025-04-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0013_alter_habit_color_alter_habit_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="color",
            field=models.CharField(
                choices=[
                    ("dodgerblue", "Bright Blue"),
                    ("crimson", "Tomato"),
                    ("gold", "Gold"),
                    ("lightpink", "Light Pink"),
                    ("olive", "Olive"),
                    ("peru", "Indian Red "),
                    ("slateblue", "Indigo"),
                    ("thistle", "Thistle"),
                ],
                default="blue",
                max_length=20,
            ),
        ),
    ]
