# Generated by Django 5.1.8 on 2025-04-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0014_alter_habit_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="is_unlimited",
            field=models.BooleanField(default=True),
        ),
    ]
