# Generated by Django 5.1.8 on 2025-04-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0015_alter_habit_is_unlimited"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="duration_days",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="is_unlimited",
        ),
    ]
